### ISSUE TITLE
log method doesn't work with Error objects

### ISSUE THREAD

**Issue by mloncaric** [deepwell/meteor-raven#1]
Please change <a href="https://github.com/deepwell/meteor-raven/blob/master/lib/main.js#L50" target="_blank">this</a> condition to:

<pre>message instanceof Error</pre>

or something similar, because right now it doesn't work with Error objects.
typeof (new Error) returns "object" and not "Error" and because of that it always calls captureMessage instead of captureException.

Thank you for making the package.

**Comment by deepwell** [comment]
Thanks for the bug report!
