### ISSUE TITLE
Turn into a raven.js plugin

### ISSUE THREAD

**Issue by mattrobenolt** [deepwell/meteor-raven#2]
Any opposition to making this a plugin that we distribute with the others? Would like to get it in https://github.com/getsentry/raven-js/tree/master/plugins :)

**Comment by deepwell** [comment]
None whatsoever, I would be happy to see you fork this code.

**Comment by mattrobenolt** [comment]
I don't know anything about meteor, so I'd rely on you to bring that in. Is it possible to bundle up this whole plugin into a single file, say, `meteor.js` that is dropped in?

**Comment by deepwell** [comment]
That's not possible (AFAIK), the only way to install a Meteor package is through Meteorite. You can see the package here:
https://atmosphere.meteor.com/package/raven

It does not work as a stand alone file. Meteor's package format works for both frontend and backend files, with minification, compression etc. done for browser sent files (not server files) on production deploy.
